server:
  context-path: /cmfz
  port: 5050
  jsp-servlet:
    init-parameters:
      development: true
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  mvc:
    view:
      suffix: .jsp
      prefix: /
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
mybatis:
  mapper-locations: classpath:com/baizhi/cmfz/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.cmfz.entity
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
  width: 150
  height: 150
  tracker-list: #TrackerList参数,支持多个
    - 192.168.56.142:22122